# Generated by Django 4.2.1 on 2023-05-12 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2023, 5, 12, 9, 11, 36, 689002))),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
