# Generated by Django 4.2.1 on 2023-05-13 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_postings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postings',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 17, 32, 37, 953565)),
        ),
        migrations.AlterField(
            model_name='postings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
