# Generated by Django 4.2.1 on 2023-05-13 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_postings_create_time_alter_postings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postings',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 17, 35, 55, 462273)),
        ),
    ]
