# Generated by Django 4.2.1 on 2023-05-13 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_postings_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postings',
            name='content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='postings',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 17, 47, 17, 771882)),
        ),
    ]
