# Generated by Django 4.2.1 on 2023-05-19 02:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_postings_content_alter_postings_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postings',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 10, 16, 43, 888558)),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 5, 19, 10, 16, 43, 888558))),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
