# Generated by Django 4.2.1 on 2023-05-22 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_postings_create_time_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 11, 15, 36, 124400)),
        ),
        migrations.AlterField(
            model_name='postings',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
